export const actionTypes = {
    ADD_EXPENSE: '@@HOME/ADD_EXPENSE',
    UPDATE_EXPENSE: '@@HOME/UPDATE_EXPENSE',
    DELETE_EXPENSE: '@@HOME/DELETE_EXPENSE',
    UPDATE_INPUT: '@@SETTINGS/UPDATE_INPUT',
    ADD_CATEGORY: '@@SETTINGS/ADD_CATEGORY',
    DELETE_CATEGORY: '@@SETTINGS/DELETE_CATEGORY',
}